############################################
# GLOBAL LLM CONFIGURATION (OPENROUTER)
############################################

[llm]
api_type = "openai"
model = "nvidia/nemotron-3-nano-30b-a3b:free"
base_url = "https://openrouter.ai/api/v1"
api_key = "key..."
max_tokens = 4000
temperature = 0.0

#[llm]
#api_type = "ollama"
#model = "wizardlm:7b-q4_0"
#base_url = "http://localhost:11434/v1"
#api_key = "ollama"
#max_tokens = 4000
#temperature = 0.0

# Primary (fast, but rate-limited)
[llm.primary]
model = "llama-3.3-70b-versatile"
base_url = "https://api.groq.com/openai/v1"
api_key = "ahhhh"
max_tokens = 4000
temperature = 0.0
# Backup (slower, but unlimited)
[llm.backup]
model = "llama-3.1-70b-versatile"
base_url = "https://api.groq.com/openai/v1"
api_key = "ahhhh"
max_tokens = 4000
temperature = 0.0
# Optional second backup
[llm.backup2]
model = "llama-3.1-8b-instant"
base_url = "https://api.groq.com/openai/v1"
api_key = "ahhhh"
max_tokens = 4000
temperature = 0.0

# Optional second backup
[llm.backup3]
model = "llama-3.3-70b-versatile"
base_url = "https://api.groq.com/openai/v1"
api_key = "key..."
max_tokens = 4000
temperature = 0.0

[llm.backup4]
api_type = "openai"
model = "nvidia/nemotron-3-nano-30b-a3b:free"
base_url = "https://openrouter.ai/api/v1"
api_key = "key..."
max_tokens = 4000
temperature = 0.0

[llm.backup5]
api_type = "cohere"
model = "embed-multilingual-v3.0"
base_url = "https://api.cohere.com/v1/embed"
api_key = "d.."
max_tokens = 4000
temperature = 0.0

############################################
# VISION MODEL (OPTIONAL)
############################################

[llm.vision]
api_type = "openai"
model = "sourceful/riverflow-v2-fast-preview"
base_url = "https://openrouter.ai/api/v1"
api_key = "key..."
max_tokens = 4096
temperature = 0.0


############################################
# MCP CONFIGURATION
############################################

[mcp]
server_reference = "app.mcp.server"


############################################
# RUNFLOW CONFIGURATION
############################################

[runflow]
use_data_analysis_agent = false


############################################
# OPTIONAL: BROWSER CONFIG (DISABLED)
############################################
# [browser]
# headless = false
# disable_security = true


############################################
# OPTIONAL: SEARCH CONFIG (DISABLED)
############################################
# [search]
# engine = "DuckDuckGo"
# lang = "en"
# country = "us"
[daytona]
enabled = false
daytona_api_key = ""
